### ISSUE TITLE
AppVeyor failure

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/qutip-feedstock#1]
@pelson I cannot access AppVeyor here to re-start. Can you? I know I can just "nudge" with a PR, but I was hoping for a better solution. (Looking at AppVeyor configuration I could not see a way to add more people to the same project :unamused:)

**Comment by pelson** [comment]
Seems that appveyor is registering them under my name... worrying:

https://ci.appveyor.com/project/pelson/qutip-feedstock

*Additionally*, the appveyor error was a bit weird:

```
Build started
git clone -q --branch=master https://github.com/conda-forge/qutip-feedstock.git C:\projects\qutip-feedstock
git checkout -qf fe33e2e5b2a082ba1ef577f39bc981c2369d47a5
Running Install scripts
rmdir C:\cygwin /s /q
appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci
Downloading from http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%
set PYTHONUNBUFFERED=1
conda install -c http://conda.binstar.org/pelson/channel/development --yes --quiet obvious-ci
Fetching package metadata: ...... 
Solving package specifications: .........................Command exited with code -1073741819
```

All the other jobs succeeded, so suspect this is noise - the next PR along worked fine!

**Comment by jakirkham** [comment]
Is this still an issue?

I had some AppVeyor failures like due to the `script` line as this use to be ignored on Windows due to this issue ( https://github.com/conda/conda-build/issues/682 ). However, it looks like this can be fixed with a simple selector and now appears to be working.

Though it looks like this might be a totally different issue.

**Comment by pelson** [comment]
Looks fine to me. Closing.
