### ISSUE TITLE
distutils.cfg not created

### ISSUE THREAD

**Issue by ajgpitch** [conda-forge/qutip-feedstock#14]
The 'trick' that I copied from the libpython package to copy the distutils.cfg file did not seem to work.
For now I am handling it in documentation.
I will try some other method later

**Comment by sahmed95** [comment]
Hi, I am trying to understand how this works. Please correct me if I am wrong.

A Windows user needs to have a compiler similar to gcc for Cython files to be compiled. It can be pymingw, Microsoft SDK or the latest released [Microsoft Visual C++ Compiler for Python 2.7
](http://www.microsoft.com/en-us/download/details.aspx?id=44266) which is recommeded strongly by Cython in their [post on Windows compilation](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows).

> always use Microsoft's compiler for C++, even on 32-bit x86

So to do this, the user needs to write the`distutils.cfg` file and mention the compiler. Currently we do not have anything that creates this .cfg file automatically ?

**Comment by ajgpitch** [comment]
We can't use the straight Microsoft SDK v7 because it does not support complex.h. Well, conda-forge complains about it being missing anyway. So we include mingwpy in the build packages. Now I think this does something clever and somehow uses (parts of) the Windows SDK in the build. 

I have been doing a lot of looking into these things while trying to resolve qutip/qutip#597. It looks like a good combination (for py27)  is Microsoft SDK v7 and mingwpy. This is the combo that is used on the conda-forge (because we tell it to be so in build.bat) to build the extensions.

Anyway, at runtime (for str time-dependent solvers), we need distutils to know that it should use the same combo (if possible, if not just the gcc in mingw), which it does through looking at the distutils.cfg

**Comment by ajgpitch** [comment]
I have a plan. I am guessing that there is something like `install.bat` that we can include these lines in:
```
if not exist %PREFIX%\Lib\distutils\ mkdir %PREFIX%\Lib\distutils\
if errorlevel 1 exit 1
echo [build]           > %PREFIX%\Lib\distutils\distutils.cfg
if errorlevel 1 exit 1
echo compiler=mingw32 >> %PREFIX%\Lib\distutils\distutils.cfg
if errorlevel 1 exit 1
```

**Comment by ajgpitch** [comment]
I spent a bit more time looking into this and there is some kind of pre / post install script, but it does not look like it has access to the same env vars as the build script so was not sure how to proceed.

Anyway, now we have a solution for MSVC and Python 3.5+, this mingw32 Python 2.7 is find of obsolete.
I'll leave this issue here as a wontfix, just in case anyone comes up with an idea.

**Comment by ajgpitch** [comment]
Due to #16 there is no point in looking for a solution to this problem.

**Comment by jakelishman** [comment]
No longer relevant since we dropped support for Python 2.7.
