### ISSUE TITLE
What rights should the qutip organisation members have?

### ISSUE THREAD

**Issue by ajgpitch** [conda-forge/qutip-feedstock#2]
This is a test really to see what I can do

**Comment by ajgpitch** [comment]
I can't add labels or assign people, which would suggest no admin rights

**Comment by ocefpaf** [comment]
You should have admin rights.

**Comment by ajgpitch** [comment]
Well, I can't seem to do anything admin like. As I say, no labelling, assigning, and I can't see the settings icon. Should we blame the striking bots?

**Comment by ajgpitch** [comment]
It doesn't seem like I can merge my PR either.

**Comment by ocefpaf** [comment]
I am turning in. But I'll take a look at this first thing tomorrow morning.

**Comment by ajgpitch** [comment]
I tried a log out and in, but still no merge button etc

**Comment by pelson** [comment]
I've fixed and re-run the script. Could you double check your permissions (you should be an admin on this repo).

**Comment by pelson** [comment]
Correction - doesn't seem to have picked up on qutip. I'm digging now.

**Comment by ajgpitch** [comment]
Yes, still no admin rights here.
Ok, well I am off out for a few hours now.

**Comment by ocefpaf** [comment]
@ajgpitch I just added you again manually as we negotiate and end to the bot strike with their union.  Let's hope this time it will sticky!

![adim](https://cloud.githubusercontent.com/assets/950575/13567871/a6513d18-e43c-11e5-9ec1-c7e3195d42fc.png)

**Comment by ajgpitch** [comment]
Yey! All good. I added a label and did a merge.
@ocefpaf  thank you

**Comment by pelson** [comment]
I think you should now have a team which has admin access to this repo. I've revoked the changes that @ocefpaf made, so if something still isn't right, please let me know. Thanks!
