### ISSUE TITLE
update numpy requirements in meta.yaml?

### ISSUE THREAD

**Issue by jfeist** [conda-forge/qutip-feedstock#27]
Currently, the numpy requirements in `meta.yaml` are written as `numpy x.x`, which does an explicit build for each version of numpy (and needs rebuilds when a new numpy is released). According to https://conda-forge.org/docs/meta.html#building-against-numpy, it should be possible to instead use 
```
build:
  - numpy 1.11.*
run:
  - numpy >=1.11
```
which, as far as I understand, would keep the package compatible with new numpy releases without requiring a rebuild, as long as numpy keeps binary compatibility.

(I noticed because right now, qutip from conda-forge is preventing the upgrade to numpy 1.14 - if this is not or cannot be changed, could a rebuild against numpy 1.14 be triggered?)

**Comment by sahmed95** [comment]
Hi, we will update this for the next release. @ajgpitch Any comments?

**Comment by nathanshammah** [comment]
We did not change this yet

**Comment by jakelishman** [comment]
Closed by #29.
