### ISSUE TITLE
Missing team members

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qutip-feedstock#5]
It is clear that @ajgpitch should be a [team member]( https://github.com/orgs/conda-forge/teams/qutip ), but he is not. Can we correct this somehow, @pelson?

**Comment by ocefpaf** [comment]
@jakirkham my memory is failing, but I do remember @pelson fixing/looking into this problem...

**Comment by ajgpitch** [comment]
Somehow I did not get automatically added, but I was manually added. I found that I did have admin rights last time I updated the stock

**Comment by jakirkham** [comment]
@ajgpitch, could you please request to join the [qutip team]( https://github.com/orgs/conda-forge/teams/qutip ) and the [all-members team]( https://github.com/orgs/conda-forge/teams/all-members )? We will approve these and get you back on-board.

**Comment by ajgpitch** [comment]
Yes, it looks like it may have been my fault. It seems I had ignored an invitation to join conda-forge on 7 Mar. It looks like I am now a member of qutip and all-members.
Thanks

**Comment by jakirkham** [comment]
Awesome.

I think you came into the system at a weird time when things were transitioning on this point of adding team members. Now it is relatively stable.

Glad you were able to get in without problems. Going to go ahead and close.
