### ISSUE TITLE
qutip__init__.patch?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/qutip-feedstock#8]
I'm trying to understand the purpose of this patch. I did skim the history of this in staged-recipes ( https://github.com/conda-forge/staged-recipes/pull/74 ), but am still not following it. I would like to know why the patch was added, whether the patch can be added upstream, if there is any issue upstream related to this patch, etc..

My concern is we find ourselves maintaining a forever patched version of `qutip`. It would be good to at least make sure that upstream is aware of the problem and we try to work with them to come up with a permanent change in their source code that obviates the need for the patch. This way we can drop at some release in the future.

If this is happening somewhere, it would be good to cross reference it here and add a comment above the patch in the recipe. This way we can track better what is going on.

**Comment by ajgpitch** [comment]
The purpose was to remove the runtime dependency on cython. When cython is installed, it recythonises everything on first import of qutip.  This can be an issue on Windows. We (the qutip admin team) have discussed this, and we have now agreed that cython will no longer be a runtime requirement. There are some features that would not be available without it, but the vast majority of the library will still work. 

We are looking to make a new release very soon. I was hoping that we would have a new member of the team by now who would sort out all the cython stuff, but it looks like this will not happen in time, so in may fall to me to implement something. But we will ensure that this patch is not necessary when we release qutip 3.2.0.

**Comment by jakirkham** [comment]
Ok, sounds good. Is there an issue or PR that documents this intended change? If so, let's add a ref to it in the comment above the patch.

**Comment by jakirkham** [comment]
Looks like this is the issue ( https://github.com/qutip/qutip/issues/448 ). Correct, @ajgpitch? Was there a PR with the patch too?

**Comment by ajgpitch** [comment]
Yes, this is the issue. There was no PR, because this patch was a quick and dirty fix. I wanted (me or someone else) to take a more broad approach to revising cythonising in qutip.

**Comment by sahmed95** [comment]
@ajgpitch We no longer have this patch. So is it safe to close this issue ?

**Comment by ajgpitch** [comment]
We'll close this issue when we have tested the qutip 4 conda packages on
Windows.
Looks like we are getting pretty close now.

**Comment by ajgpitch** [comment]
Windows packages produced by #12 are working well, demonstrating that this patch is definitely no longer needed
